### ISSUE TITLE
Add imports

### ISSUE THREAD

**Issue by danielo515** [tmarun/vscode-material-ui-snippets#2]
Hello,

Thanks for this extension, it certainly saves time. But for it being even more time saving it would be awesome to include the imports of the different components. Probably is a better idea to make them separate snippets, so you can choose where and how do you put them.

Thanks!

**Comment by buixuanhai** [comment]
Good idead

**Comment by tmarun** [comment]
Will work on this. Thanks

**Comment by danielo515** [comment]
I suppose you closed it because it is now implemented?
